{% set name = "pyfuse3" %}
{% set version = "3.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyfuse3-{{ version }}.tar.gz
  sha256: 2b31fe412479f9620da2067dd739ed23f4cc37364224891938dedf7766e573bd

build:
  number: 1
  skip: true  # [not linux64]
  script:
    - {{ PYTHON }} setup.py build_cython
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - python
    - pip
    - cython
    - libfuse
  run:
    - python
    - trio >=0.15
    - libfuse

test:
  imports:
    - pyfuse3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/libfuse/pyfuse3
  summary: Python 3 bindings for libfuse 3 with async I/O support
  license: LGPL-2.1-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
